In [ ]:
import numpy as np
from scipy import sparse



In [20]:
# Create a 2D Numpy array with a diagonal of ones, and zeros everywhere else
import numpy as np
from scipy import sparse
eye = np.eye(10)
print("Numpy array:\n", eye)

Numpy array:
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [5]:
# Convert the Numpy array to a SciPy sparse matrix in CSR format
# Only the nonzero entries are stored 
'''The Compressed Sparse Row (CSR) format is a way of efficiently storing and operating on sparse matrices in scientific computing, 
particularly using libraries like SciPy. Sparse matrices are matrices that contain a large number of zero elements,
 and the CSR format helps save memory and improve computation speed by storing only the non-zero elements and their positions.'''
sparse_matrix= sparse.csr_matrix(eye)
print("\nSciPy sparse CSR matrix:\n", sparse_matrix)


SciPy sparse CSR matrix:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0
  (5, 5)	1.0
  (6, 6)	1.0
  (7, 7)	1.0
  (8, 8)	1.0
  (9, 9)	1.0


In [7]:
'''Coordinate (COO) format is a way to store sparse matrices by listing the row and column indices of non-zero elements.
 It's a simple and intuitive format that's useful for building sparse matrices incrementally'''
# COO representation 
data = np.ones(4)
row_indices = np.arange(4)
col_indices = np.arange(4)
eye_coo = sparse.coo_matrix((data,(row_indices,col_indices)))
print("COO representation:\n", eye_coo)

COO representation:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [27]:
# Matplotlib is for visualizations
import matplotlib.pyplot as plt



ModuleNotFoundError: No module named 'matplotlib'

In [1]:
# Pandas is a Python Library for data wrangling
# It is built around a data structure called a DataFrame
# DataFrame is a table
# Pandas allows each column to be of a different type
import pandas as pd
# Create a simple dataset of people
data = {'Name':["John", "Anna", "Kgosi", "Elmoen"],
        'Location':["New York", "Johannesburg", "Sandton", "Cape Town"],
        'Age':[24,34,33,26]}
data_pandas=pd.DataFrame(data)
# IPython.display allows "pretty printing" of dataframes
# In the Jupyter Notebook
display(data_pandas)

Name      Location  Age
0    John      New York   24
1    Anna  Johannesburg   34
2   Kgosi       Sandton   33
3  Elmoen     Cape Town   26